Changes: core->_SoftmaxTfModel -> SoftmaxTfModel
 metrics.reset_states() -> metrics.reset_state()
 remove 0 from the dataset

In [10]:
import tensorflow as tf
import ltn
import baselines, data, commons
import matplotlib.pyplot as plt
import numpy as np

# Dataset preprocessing
## Importing dataset

In [11]:
mnist = tf.keras.datasets.mnist
(img_train, label_train), (img_test, label_test) = mnist.load_data()

# normalising the pixel values
img_train, img_test = img_train/255.0, img_test/255.0

# adding a channel dimension for compatibility with the convolutional layers
img_train = img_train[...,tf.newaxis]
img_test = img_test[...,tf.newaxis]

## Removing images with the 0 digit

In [12]:
# train data without label 0
not_zeros_train = label_train != 0
img_train = img_train[not_zeros_train]
label_train = label_train[not_zeros_train]

#test data without label 0
not_zeros_test = label_test != 0
img_test = img_test[not_zeros_test]
label_test = label_test[not_zeros_test]

# how much data will be considered
count_train = 10000
count_test = 3000
n_operands = 2

# operation
op = lambda args: args[0]%args[1]

# train data
img_per_operand_train = [img_train[i*count_train:i*count_train+count_train] for i in range(n_operands)]
label_per_operand_train = [label_train[i*count_train:i*count_train+count_train] for i in range(n_operands)]
label_result_train = np.apply_along_axis(op,0,label_per_operand_train)

# test data
img_per_operand_test = [img_test[i*count_test:i*count_test+count_test] for i in range(n_operands)]
label_per_operand_test = [label_test[i*count_test:i*count_test+count_test] for i in range(n_operands)]
label_result_test = np.apply_along_axis(op,0,label_per_operand_test)

## Creating tf datasets of specific buffer and batch size

In [13]:
# dataset parameters
buffer_size = 3000
batch_size = 16
    
# making the train dataset
ds_train = tf.data.Dataset.from_tensor_slices(tuple(img_per_operand_train)+(label_result_train,))\
            .take(count_train).shuffle(buffer_size).batch(batch_size)

#making the test dataset
ds_test = tf.data.Dataset.from_tensor_slices(tuple(img_per_operand_test)+(label_result_test,))\
            .take(count_test).shuffle(buffer_size).batch(batch_size)

## LTN

In [14]:
logits_model = baselines.SingleDigit(inputs_as_a_list=True)
Digit = ltn.Predicate.FromLogits(logits_model, activation_function="softmax")

d1 = ltn.Variable("digits1", range(10))
d2 = ltn.Variable("digits2", range(10))

Not = ltn.Wrapper_Connective(ltn.fuzzy_ops.Not_Std())
And = ltn.Wrapper_Connective(ltn.fuzzy_ops.And_Prod())
Or = ltn.Wrapper_Connective(ltn.fuzzy_ops.Or_ProbSum())
Implies = ltn.Wrapper_Connective(ltn.fuzzy_ops.Implies_Reichenbach())
Forall = ltn.Wrapper_Quantifier(ltn.fuzzy_ops.Aggreg_pMeanError(),semantics="forall")
Exists = ltn.Wrapper_Quantifier(ltn.fuzzy_ops.Aggreg_pMean(),semantics="exists")

In [15]:
# mask
modulo = ltn.Function.Lambda(lambda inputs: inputs[0] % inputs[1])
equals = ltn.Predicate.Lambda(lambda inputs: inputs[0] == inputs[1])

### Axioms
@tf.function
def axioms(images_x, images_y, labels_z, p_schedule=tf.constant(2.)):
    images_x = ltn.Variable("x", images_x)
    images_y = ltn.Variable("y", images_y)
    labels_z = ltn.Variable("z", labels_z)
    axiom = Forall(
            ltn.diag(images_x,images_y,labels_z),
            Exists(
                (d1,d2),
                And(Digit([images_x,d1]),Digit([images_y,d2])),
                mask=equals([modulo([d1,d2]), labels_z]),
                p=p_schedule
            ),
            p=2
        )
    sat = axiom.tensor
    return sat

images_x, images_y, labels_z = next(ds_train.as_numpy_iterator())
axioms(images_x, images_y, labels_z)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009809792041778564>

Optimizer, training steps and metrics

In [16]:
optimizer = tf.keras.optimizers.Adam(0.001)
metrics_dict = {
    'train_loss': tf.keras.metrics.Mean(name="train_loss"),
    'train_accuracy': tf.keras.metrics.Mean(name="train_accuracy"),
    'test_loss': tf.keras.metrics.Mean(name="test_loss"),
    'test_accuracy': tf.keras.metrics.Mean(name="test_accuracy")    
}

@tf.function
def train_step(images_x, images_y, labels_z, **parameters):
    # loss
    with tf.GradientTape() as tape:
        loss = 1.- axioms(images_x, images_y, labels_z, **parameters)
    gradients = tape.gradient(loss, logits_model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, logits_model.trainable_variables))
    metrics_dict['train_loss'](loss)
    # accuracy
    predictions_x = tf.argmax(logits_model([images_x]),axis=-1)
    predictions_y = tf.argmax(logits_model([images_y]),axis=-1)
    predictions_z = predictions_x % predictions_y
    match = tf.equal(predictions_z,tf.cast(labels_z,predictions_z.dtype))
    metrics_dict['train_accuracy'](tf.reduce_mean(tf.cast(match,tf.float32)))
    
@tf.function
def test_step(images_x, images_y, labels_z,is_poison, **parameters):
    # loss
    loss = 1.- axioms(images_x, images_y, labels_z, **parameters)
    metrics_dict['test_loss'](loss)
    # accuracy
    predictions_x = tf.argmax(logits_model([images_x]),axis=-1)
    predictions_y = tf.argmax(logits_model([images_y]),axis=-1)
    predictions_z = predictions_x % predictions_y
    match = tf.equal(predictions_z,tf.cast(labels_z,predictions_z.dtype))
    metrics_dict['test_accuracy'](tf.reduce_mean(tf.cast(match,tf.float32)))

Training

In [17]:
from collections import defaultdict

scheduled_parameters = defaultdict(lambda: {})
for epoch in range(0,4):
    scheduled_parameters[epoch] = {"p_schedule":tf.constant(1.)}
for epoch in range(4,8):
    scheduled_parameters[epoch] = {"p_schedule":tf.constant(2.)}
for epoch in range(8,12):
    scheduled_parameters[epoch] = {"p_schedule":tf.constant(4.)}
for epoch in range(12,20):
    scheduled_parameters[epoch] = {"p_schedule":tf.constant(6.)}


In [18]:
commons.train(
    epochs= 20,
    metrics_dict= metrics_dict,
    ds_train= ds_train,
    ds_test_clean= ds_test,
    ds_test_poisoned= None,
    train_step= train_step,
    test_step= test_step,
    scheduled_parameters=scheduled_parameters
)

Epoch 0, train_loss: 0.9260, train_accuracy: 0.8210, test_loss: 0.9153, test_accuracy: 0.8936
Epoch 1, train_loss: 0.9140, train_accuracy: 0.9150, test_loss: 0.9120, test_accuracy: 0.9265
Epoch 2, train_loss: 0.9113, train_accuracy: 0.9381, test_loss: 0.9132, test_accuracy: 0.9176
Epoch 3, train_loss: 0.9107, train_accuracy: 0.9367, test_loss: 0.9145, test_accuracy: 0.9039
Epoch 4, train_loss: 0.7499, train_accuracy: 0.9342, test_loss: 0.7478, test_accuracy: 0.9302
Epoch 5, train_loss: 0.7408, train_accuracy: 0.9562, test_loss: 0.7440, test_accuracy: 0.9392
Epoch 6, train_loss: 0.7402, train_accuracy: 0.9558, test_loss: 0.7494, test_accuracy: 0.9252
Epoch 7, train_loss: 0.7402, train_accuracy: 0.9577, test_loss: 0.7425, test_accuracy: 0.9428
Epoch 8, train_loss: 0.5314, train_accuracy: 0.9481, test_loss: 0.5942, test_accuracy: 0.8547
Epoch 9, train_loss: 0.5283, train_accuracy: 0.9501, test_loss: 0.5320, test_accuracy: 0.9395
Epoch 10, train_loss: 0.5258, train_accuracy: 0.9536, test_l

{'train_loss': [<tf.Tensor: shape=(), dtype=float32, numpy=0.925950288772583>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.9139537811279297>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.9112563729286194>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.9106729626655579>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.7499480247497559>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.7407801151275635>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.7402399182319641>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.7401671409606934>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.531449556350708>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.5282751321792603>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.5257507562637329>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.5184871554374695>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.4172307252883911>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.41073739528656006>,
  <tf.Tensor: shape=(), dtype=float32, numpy=0.40677410364151>,